// Pokemon type color mappings for Tailwind CSS with vibrant gradients
export const typeColors: { [key: string]: string } = {
  normal: 'bg-gradient-to-br from-gray-400 to-gray-500',
  fire: 'bg-gradient-to-br from-red-500 to-orange-600',
  water: 'bg-gradient-to-br from-blue-500 to-cyan-600',
  electric: 'bg-gradient-to-br from-yellow-400 to-yellow-500',
  grass: 'bg-gradient-to-br from-green-500 to-emerald-600',
  ice: 'bg-gradient-to-br from-cyan-400 to-blue-400',
  fighting: 'bg-gradient-to-br from-red-700 to-red-800',
  poison: 'bg-gradient-to-br from-purple-500 to-purple-700',
  ground: 'bg-gradient-to-br from-yellow-600 to-amber-700',
  flying: 'bg-gradient-to-br from-indigo-400 to-blue-500',
  psychic: 'bg-gradient-to-br from-pink-500 to-purple-500',
  bug: 'bg-gradient-to-br from-lime-500 to-green-600',
  rock: 'bg-gradient-to-br from-yellow-700 to-stone-800',
  ghost: 'bg-gradient-to-br from-purple-700 to-indigo-900',
  dragon: 'bg-gradient-to-br from-indigo-600 to-purple-700',
  dark: 'bg-gradient-to-br from-gray-700 to-gray-900',
  steel: 'bg-gradient-to-br from-gray-500 to-slate-600',
  fairy: 'bg-gradient-to-br from-pink-400 to-pink-500',
};
